# Default values for total_invoice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replica_count: 1
namespace: default

# If set to "http", logs will be pushed to fluentd sidecar using JSON lines over HTTP protocol
#
# If set to "console", logs will be captured by fluentd sidecar from stdout/stderr
#
# If set to "ai_native", fluentd sidecar will not be used at all. The deployment will assume
# that services are pushing logs to Application Insights directly using AI SDK 
#
# If set to "ai_sidecar", AI SDK will write to the endpoint implemented by the fluentd sidecar
# as opposed to default Breeze (Azure Application Insights service) endpoint. 
# This guarantees full telemetry type support while leveraging sidecar to provide Kubernetes context.  
log_capture_mode: ai_sidecar

# In production environment the auth token should not have a default value
# (it should be passed via command-line parameter at deployment time)
auth_token: letmeinpleasekthxbye

invoices_svc_image: yanmingacr.azurecr.io/invoices_svc
expected_date_svc_image: yanmingacr.azurecr.io/expected_date_svc
auth_svc_image: yanmingacr.azurecr.io/auth_svc
audit_svc_image: yanmingacr.azurecr.io/audit_svc
entry_svc_image: yanmingacr.azurecr.io/entry_svc
ambassador_svc_image: quay.io/datawire/ambassador:0.34.0
ambassador_svc_statsd_image: quay.io/datawire/statsd:0.34.0
fluentdsidecar_image: yanmingacr.azurecr.io/fluentdsidecar:latest